services:
  server:
    container_name: server-dev
    build:
      target: server-dev
    volumes:
      - ./server/src:/app/server:ro
    environment:
      - DATABASE_USE_SSL=false
  # We only need a front-end container in dev - in production we'll
  # build into a static bundle.
  client:
    container_name: client-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: client-dev
    environment:
      - VITE_PORT=3000
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    volumes:
      - ./client/:/app/client:ro
  proxy:
    container_name: proxy-dev
    build:
      target: dev
    ports:
      - "${STACK_PORT}:80"
  psql-dev:
    init: true
    container_name: psql-dev
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h psql-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      PGUSER: ${PSQL_USERNAME}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB}
      PGPORT: 5432
    ports:
      - ${PSQL_PORT}:5432
    volumes:
     - psql-dev-data:/var/lib/postgresql/data

volumes:
  psql-dev-data:
