services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
      - DATABASE_HOST=${PSQL_HOST}
      - DATABASE_USER=${PSQL_USERNAME}
      - DATABASE_PASSWORD=${PSQL_PASSWORD}
      - DATABASE_NAME=${PSQL_DB}
      - DATABASE_PORT=${PSQL_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_BOT_SERVER_ID=${DISCORD_BOT_SERVER_ID}
      - DISCORD_BOT_CHANNEL_ID=${DISCORD_BOT_CHANNEL_ID}
  proxy:
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile
