services:
  server:
    container_name: server-dev
    build:
      target: dev
    volumes:
      - ./server/src:/app/src:ro
  # We only need a front-end container in dev - in production we'll
  # build into a static bundle.
  client:
    container_name: client-dev
    build:
      context: ./client
      target: dev
    environment:
      - VITE_PORT=3000
    volumes:
      - ./client/src:/app/src:ro
      - ./client/index.html:/app/index.html:ro
      - ./client/public:/app/public:ro
  proxy:
    container_name: proxy-dev
    build:
      target: dev
