services:
  server:
    image: registry.gitlab.com/ugo-ii/scr4m/server:${IMAGE_VERSION}
    container_name: server-prod
    build:
      target: server-prod
    environment:
      - DATABASE_USE_SSL=true
      - USE_SECURE_SESSION_COOKIE=true

  proxy:
    image: registry.gitlab.com/ugo-ii/scr4m/proxy:${IMAGE_VERSION}
    container_name: proxy-prod
    build:
      target: prod
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - 443:443
    volumes:
      - /etc/letsencrypt/live/scr4m.ugo-ii.com/fullchain.pem:/cert/fullchain.pem:ro
      - /etc/letsencrypt/live/scr4m.ugo-ii.com/privkey.pem:/cert/privkey.pem:ro