name: Biome
on:
  pull_request:

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Typecheck
        run: pnpm run -r tscheck
      - name: Run Biome
        run: biome ci .